services:
  - type: web
    name: sana-corp
    env: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -Dspring.profiles.active=prod -jar target/administrador-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: sana-corp-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: sana-corp-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sana-corp-db
          property: password

databases:
  - name: sana-corp-db
    databaseName: hospital_virtual
    user: sanacorp